# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 500)
        MainWindow.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel.setGeometry(QtCore.QRect(10, 10, 341, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.outputlabel.setFont(font)
        self.outputlabel.setStyleSheet("background-color: rgb(83, 83, 83);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.outputlabel.setFrameShape(QtWidgets.QFrame.Panel)
        self.outputlabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputlabel.setText("")
        self.outputlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputlabel.setObjectName("outputlabel")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("%"))
        self.percentButton.setGeometry(QtCore.QRect(100, 100, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.percentButton.setFont(font)
        self.percentButton.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.percentButton.setObjectName("percentButton")
        self.copyButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("AC"))
        self.copyButton.setGeometry(QtCore.QRect(10, 100, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.copyButton.setFont(font)
        self.copyButton.setStyleSheet("background-color: rgb(165, 165, 165);\n"
"")
        self.copyButton.setObjectName("copyButton")
        self.arrowButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.remove_it())
        self.arrowButton.setGeometry(QtCore.QRect(280, 100, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.arrowButton.setFont(font)
        self.arrowButton.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.arrowButton.setObjectName("arrowButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("/"))
        self.divideButton.setGeometry(QtCore.QRect(280, 180, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.divideButton.setFont(font)
        self.divideButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(217, 145, 0);")
        self.divideButton.setObjectName("divideButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("7"))
        self.sevenButton.setGeometry(QtCore.QRect(10, 180, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.sevenButton.setFont(font)
        self.sevenButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.sevenButton.setObjectName("sevenButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("*"))
        self.multiplyButton.setGeometry(QtCore.QRect(280, 260, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(217, 145, 0);")
        self.multiplyButton.setObjectName("multiplyButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("8"))
        self.eightButton.setGeometry(QtCore.QRect(100, 180, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.eightButton.setFont(font)
        self.eightButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.eightButton.setObjectName("eightButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("9"))
        self.nineButton.setGeometry(QtCore.QRect(190, 180, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.nineButton.setFont(font)
        self.nineButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.nineButton.setObjectName("nineButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("4"))
        self.fourButton.setGeometry(QtCore.QRect(10, 260, 80, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.fourButton.setFont(font)
        self.fourButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.fourButton.setObjectName("fourButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("1"))
        self.oneButton.setGeometry(QtCore.QRect(10, 340, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.oneButton.setFont(font)
        self.oneButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.oneButton.setObjectName("oneButton")
        self.plusminusButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.plus_minus_it())
        self.plusminusButton.setGeometry(QtCore.QRect(190, 100, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.plusminusButton.setFont(font)
        self.plusminusButton.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.plusminusButton.setObjectName("plusminusButton")
        self.fivebutton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("5"))
        self.fivebutton.setGeometry(QtCore.QRect(100, 260, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.fivebutton.setFont(font)
        self.fivebutton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.fivebutton.setObjectName("fivebutton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("6"))
        self.sixButton.setGeometry(QtCore.QRect(190, 260, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.sixButton.setFont(font)
        self.sixButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.sixButton.setObjectName("sixButton")
        self.minusButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("-"))
        self.minusButton.setGeometry(QtCore.QRect(280, 340, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.minusButton.setFont(font)
        self.minusButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(217, 145, 0);")
        self.minusButton.setObjectName("minusButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("2"))
        self.twoButton.setGeometry(QtCore.QRect(100, 340, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.twoButton.setFont(font)
        self.twoButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.twoButton.setObjectName("twoButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("3"))
        self.threeButton.setGeometry(QtCore.QRect(190, 340, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.threeButton.setFont(font)
        self.threeButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.threeButton.setObjectName("threeButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("+"))
        self.addButton.setGeometry(QtCore.QRect(280, 420, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(217, 145, 0);")
        self.addButton.setObjectName("addButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_if("0"))
        self.zeroButton.setGeometry(QtCore.QRect(10, 420, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.zeroButton.setFont(font)
        self.zeroButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.zeroButton.setObjectName("zeroButton")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.dot_it())
        self.decimalButton.setGeometry(QtCore.QRect(100, 420, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.decimalButton.setFont(font)
        self.decimalButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.decimalButton.setObjectName("decimalButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.equal_it())
        self.equalButton.setGeometry(QtCore.QRect(190, 420, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.equalButton.setFont(font)
        self.equalButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: red;")
        self.equalButton.setObjectName("equalButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    #remove character
    def remove_it(self):
        screen = self.outputlabel.text()
        screen = screen[:-1]
        self.outputlabel.setText(screen)
    # equal to button
    def equal_it(self):
        screen = self.outputlabel.text()
        try:
            answer = eval(screen)
            self.outputlabel.setText(str(answer))
        except:
            self.outputlabel.setText("error")
    # change from positive/negative
    def plus_minus_it(self):
        screen = self.outputlabel.text()
        if "-" in screen:
            self.outputlabel.setText(screen.replace("-", ""))
        else:
            self.outputlabel.setText(f"-{screen}")
    #add a decimal 
    def dot_it(self):
        screen = self.outputlabel.text()
        if screen[-1] == ".":
            pass
        else:
            self.outputlabel.setText(f"{screen}.")

    def press_if(self, pressed):
        if pressed == "AC":
            self.outputlabel.setText("0")
        else:
             if self.outputlabel.text() == "0":
                 self.outputlabel.setText("")
             self.outputlabel.setText(f"{self.outputlabel.text()}{pressed}")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.copyButton.setText(_translate("MainWindow", "AC"))
        self.arrowButton.setText(_translate("MainWindow", "<<"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.multiplyButton.setText(_translate("MainWindow", "*"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.plusminusButton.setText(_translate("MainWindow", "+/-"))
        self.fivebutton.setText(_translate("MainWindow", "5"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.addButton.setText(_translate("MainWindow", "+"))
        self.zeroButton.setText(_translate("MainWindow", "0"))
        self.decimalButton.setText(_translate("MainWindow", "."))
        self.equalButton.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    MainWindow.setFixedWidth(361)
    MainWindow.setFixedHeight(500)
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
